#!/bin/sh

# install homebrew if it's missing
if ! command -v brew >/dev/null 2>&1; then
    echo "-------------------"
    echo "Installing homebrew"
    echo "-------------------"
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
    eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"

    if command -v apt-get >/dev/null 2>&1; then
        echo "------------------------"
        echo "Installing homebrew deps"
        echo "------------------------"
        sudo apt-get install -y build-essential procps curl file git
    fi
fi

if [ -f "$HOME/.Brewfile" ]; then
    echo "------------------------"
    echo "Updating homebrew bundle"
    echo "------------------------"
    brew bundle --global
fi
