#!/bin/bash

echo "-----------------------"
echo "Linking VSCode settings"
echo "-----------------------"

system_type=$(uname -s)
settings_loc="$HOME/.config/vscode/settings.json"
vscode_dir=""

if [ "$system_type" = "Darwin" ]; then
    vscode_dir="$HOME/Library/Application Support/Code/User"
elif [ "$system_type" = "Linux" ]; then
    vscode_dir="$HOME/.config/Code/User"
fi

mkdir -p "$vscode_dir"

if [ ! -L "$vscode_dir/settings.json" ]; then
    echo "Linking '$settings_loc' to '$vscode_dir'"
    ln -s "$settings_loc" "$vscode_dir"
else
    echo "settings file is already linked at '$vscode_dir', skipping..."
fi
