#!/usr/bin/env bash

echo "------------"
echo "Setup GitHub"
echo "------------"

if ! gh auth status >/dev/null 2>&1; then
    gh auth login -h github.com \
        --git-protocol ssh \
        --web
fi

name="$(gh api -q .name user)"
username="$(gh api -q .login user)"
id="$(gh api -q .id user)"
email="${id}+${username}@users.noreply.github.com"
echo "Setting git config user.name to '${name}'"
git config --global user.name "${name}"
echo "Setting git config user.email to '${email}'"
git config --global user.email "${email}"
git config --global merge.tool "nvim"
git config --global diff.tool "nvim"
git config --global core.editor "nvim"
git config --global commit.gpgsign "true"
git config --global init.defaultbranch "main"
