#!/usr/bin/env bash

if ! gh auth status >/dev/null 2>&1; then
    echo "-------------------------"
    echo "Running GitHub auth login"
    echo "-------------------------"
    gh auth login -h github.com -s user:email
fi

name="$(gh api -q .name user)"
email="$(gh api user/emails -t '{{ range . }}{{ if .visibility }}{{ else }}{{ .email }}{{ end }}{{ end }}')"
echo "Setting git config user.name to '${name}'"
git config --global user.name "${name}"
echo "Setting git config user.email to '${email}'"
git config --global user.email "${email}"
git config --global merge.tool "nvim"
git config --global diff.tool "nvim"
git config --global core.editor "nvim"
