traefik:
    env: ENC[AES256_GCM,data:ZEInavM7kTyb76jcf/TnD9D2lL1xP+wM6jD0vitpdLDLkRmUsw1plMPhJoIsGe9AwTvznjlz76AYO2DOkfjV5tk1HfsrG16DKkzj18OJWhhMNJw9gF+LBmrQiBHzL/Y0/6hRivLNO7mmsO+DonEuUIT7LnEMaWlL5tIFm7sXPf9Grob+xVJ3UXTAOXBRNGyDZkzubUxrVVwBiYykSTa7NGIoCURTfvEZOoTIicR0T+oxtRRn2vubcZPD7Go2aXZDRkJkMIijqnSZRd+cQQdDrpzf92pKfxA=,iv:of4sk4TDiMQWxsy+0rMpY1ZmflI3WRKgmghZ8DK+Ptg=,tag:aYFqHd+pzFWRmPxDsQc24A==,type:str]
pocket-id:
    env: ENC[AES256_GCM,data:5rGZGZYPwE5zz6ZeNdb8g4OmRqHZxWAW9Xp97KHu4TRVE/8W8bCKvuVnXWUmrCbaO8La0GfABArWTKBv84E=,iv:8bBdydQcWuYIB7v4L0IgSwheRAzcuO/MI1KyMBtiq9g=,tag:iuaj53Zm5jsIheHiVD9dFg==,type:str]
sops:
    age:
        - recipient: age1axcv7w765ja3fcg8syu43a8xeq2kzaumnst9sslhgulx4h8dfvfq5xp9np
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhOVU3RXpORDhaYkN1MDFo
            NWo3c1l6aEhQdFYrUzJnYkhtQ0xyZU1mQnpBCjI5VEt2SFlQOENxeWxseHNTTTRw
            ZFdsVTd1bTQyTThkc3cwYi9Da0U3N2sKLS0tIHVGRVlOYTEyREhmVjdBekhxMUhk
            bUs0RmovT1BwVENkYnVzQ0tsT1BWODAKs5zmJzn5lfTLnzwmEW11tU9WzpHXSigP
            BFLH9NDTWSzslu/FXPeNsvrAc4+xYo8rlanBppLr2XFsnidcLv1FHg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-15T04:31:37Z"
    mac: ENC[AES256_GCM,data:AbWgYX4JW77JObOwDCYZ8GKeOZv8vIEo4XEK3Idn/W3gP9bLT7t2bGx0HRwScW8f9tg/YRnExuJSuL7+KBgCtkelk/K/HKWB8XIjo5XcMxphUJ6L3Blh73R9dbu1xTTm1+jZP4KRrQ7jhw2zFnQz5YXR6XxDbse+repnSBa98DY=,iv:oXXZ/RyB2qCXpXmNtGnihtCj58OAOKbkocRfGZEhbO8=,tag:6Q/ECJzt6lwUFC0wUekrgg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
