traefik:
    env: ENC[AES256_GCM,data:SKHyTjh+fSmk22d2/Fv7I/RgFAqj6UxBdKF38aYFxRukGTraBTZDFMQ1qu6RnzcnV3sKw3pnGQpNtb1LJRxV7iB+ZZAZXerHZwwCEj1d5ZfLyUa1zLBcoTcP5x3WJqUN6DX8QHBS+MhBatKFfh0jF+oEDVVOiryiZN0I0xa85j8YWuK5gNsYF0K9Uu3ZJ3JRZXFmTDJJ+yWOKJHeKsVU/bJvREHiH9SR,iv:/lMGxSoyCePYe4WuFQiiVy4AEYZ8R2ulOeJGSA2f69E=,tag:EnFf+p4je9Hew9uJvPkf5w==,type:str]
pocket-id:
    env: ENC[AES256_GCM,data:L3cwU4D8LPKcdA4CwAUUbCQa2ljSJ2cgP9xDFXse8Imfqhl2VbBl7cxIhVNueuERmLGWX8g7qU71zWS3DdY=,iv:zyRY+pdCZAKkc03eySZDGNJoBFI4m8Awb/uQJ434QeY=,tag:JTAkfYeq1XFnCMPG3r9roQ==,type:str]
sops:
    age:
        - recipient: age1axcv7w765ja3fcg8syu43a8xeq2kzaumnst9sslhgulx4h8dfvfq5xp9np
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0YkpqNmNtZ1JkMG4xSkpn
            aXdHa25yTlBFK1ZqSHpRM2VDNjNKcFBwWWxBCklkWU5FV09qUUJxS0piYllqNlJT
            RVFvOGx2YmV2RTNSTmxxSE5oTXNDTmcKLS0tIEMxbE52L2k1Z3p4SC9MakR3V2Vl
            eGxZdkVna09sN2x2cGovcktjWVUyUWsKO73L0APxTfpmGusSQlOdwRH5nIogxr8O
            BFPU8sNPbf+XJCdMEh63SrCM1Bdgp808ARoDRrtEbWjdN0+grwgDHA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-15T04:00:25Z"
    mac: ENC[AES256_GCM,data:ltOzWA40mXI3TS7Z4SFWx9p6uw1VxMKqD4fKLRDz6QWg3CXDuNMiSCWTgu3EHydc5ntmR0qRmojlk17BH+PHFpbiAKBR5KQinFFjkVdELufMGglFJBZSpSDwk8HakOAM8OgOfm4D9auOegIpdxbAIVoTzTQIvXI6Oq8x6iFwgr0=,iv:rPOCDlHMhfHn38IpzGtj03+/w7JQlv28Gnts8oAqeXc=,tag:IyJ1vru8APlcMrYgpRnnFA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
