# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = ["xhci_pci" "ahci" "nvme" "usb_storage" "usbhid" "sd_mod"];
  boot.initrd.kernelModules = [];
  boot.kernelModules = ["kvm-amd"];
  boot.extraModulePackages = [];
  boot.supportedFilesystems.zfs = true;

  environment.etc."crypttab".text = ''
    # Name            UUID                                               Keyfile
    ssd_pool1         UUID=6f2f7f2b-c5e4-441f-988e-3bf5f1d92970          /var/lib/secrets/data.key
    ssd_pool2         UUID=25b86ef8-d936-400c-b54e-98cd362f6251          /var/lib/secrets/data.key
    ssd_pool3         UUID=1f4d139d-5441-4c47-8cbc-cc110b8513d2          /var/lib/secrets/data.key
    ssd_pool4         UUID=c0f82819-c7e9-412d-bec0-222473e73681          /var/lib/secrets/data.key

    ext_pool1         UUID=7e22ac54-07b0-4157-8a01-97b87d708c19          /var/lib/secrets/data.key
    ext_pool2         UUID=08ef1925-a3db-4fff-80df-a9e21fa68578          /var/lib/secrets/data.key
  '';

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/18012e8f-6414-45ff-a364-f23e4bb4cae6";
    fsType = "ext4";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/6482-84CB";
    fsType = "vfat";
    options = ["fmask=0077" "dmask=0077"];
  };

  fileSystems."/ssd_pool" = {
    device = "ssd_pool/main";
    fsType = "zfs";
  };

  fileSystems."/ext_pool" = {
    device = "ext_pool/main";
    fsType = "zfs";
  };

  swapDevices = [];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp5s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp4s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
