{
  lib,
  pkgs,
}: let
  # btop.conf renderer matching home-manager's programs.btop output (sorted
  # keys, True/False booleans, quoted strings) so the baked config diffs
  # cleanly against what HM used to write.
  renderValue = v:
    if lib.isBool v
    then
      (
        if v
        then "True"
        else "False"
      )
    else if lib.isString v
    then ''"${v}"''
    else toString v;
  renderConf = settings:
    lib.concatStrings (lib.mapAttrsToList (k: v: "${k} = ${renderValue v}\n") settings);

  # Theming ported from stylix's btop home-manager target at the pinned stylix
  # rev, so the wrapper looks identical to the HM-stylix setup it replaces:
  # https://github.com/nix-community/stylix/blob/a378e4c09031fb15a4d65da88aa628f71fc52f6b/modules/btop/hm.nix
  themeFile = theme: let
    c = lib.mapAttrs (_: hex: "#${hex}") theme.colors;
  in ''
    #Generated by Stylix
    theme[main_bg]="${c.base00}"
    theme[main_fg]="${c.base05}"
    theme[title]="${c.base05}"
    theme[hi_fg]="${c.base0D}"
    theme[selected_bg]="${c.base03}"
    theme[selected_fg]="${c.base0D}"
    theme[inactive_fg]="${c.base04}"
    theme[graph_text]="${c.base06}"
    theme[meter_bg]="${c.base03}"
    theme[proc_misc]="${c.base06}"
    theme[cpu_box]="${c.base0E}"
    theme[mem_box]="${c.base0B}"
    theme[net_box]="${c.base0C}"
    theme[proc_box]="${c.base0D}"
    theme[div_line]="${c.base01}"
    theme[temp_start]="${c.base0B}"
    theme[temp_mid]="${c.base0A}"
    theme[temp_end]="${c.base08}"
    theme[cpu_start]="${c.base0B}"
    theme[cpu_mid]="${c.base0A}"
    theme[cpu_end]="${c.base08}"
    theme[free_start]="${c.base0A}"
    theme[free_mid]="${c.base0B}"
    theme[free_end]="${c.base0B}"
    theme[cached_start]="${c.base0C}"
    theme[cached_mid]="${c.base0C}"
    theme[cached_end]="${c.base0A}"
    theme[available_start]="${c.base08}"
    theme[available_mid]="${c.base0A}"
    theme[available_end]="${c.base0B}"
    theme[used_start]="${c.base0A}"
    theme[used_mid]="${c.base09}"
    theme[used_end]="${c.base08}"
    theme[download_start]="${c.base0B}"
    theme[download_mid]="${c.base0A}"
    theme[download_end]="${c.base08}"
    theme[upload_start]="${c.base0B}"
    theme[upload_mid]="${c.base0A}"
    theme[upload_end]="${c.base08}"
    theme[process_start]="${c.base0B}"
    theme[process_mid]="${c.base0A}"
    theme[process_end]="${c.base08}"
  '';
in {
  name = "btop";
  defaultPackage = "btop";
  themeable = true;

  options = {
    settings = lib.mkOption {
      type = lib.types.attrsOf (lib.types.oneOf [lib.types.bool lib.types.int lib.types.float lib.types.str]);
      default = {};
      example = {
        vim_keys = true;
        update_ms = 2000;
      };
      description = ''
        btop config (<https://github.com/aristocratos/btop#configurability>)
        baked into the wrapper and loaded with btop's `--config` flag. The
        baked file lives in the store, so btop's save-on-exit writes fail
        with a logged warning — settings are declarative-only, same as under
        the home-manager symlink this replaces. `~/.config/btop/themes` stays
        the default user dir, so runtime-installed user themes keep working.
      '';
    };
  };

  settingsDefaults = {theme ? null, ...}:
    lib.optionalAttrs (theme != null) (
      {color_theme = "stylix";}
      // lib.optionalAttrs ((theme.opacity.terminal or 1.0) != 1.0) {
        theme_background = false;
      }
    );

  build = {
    cfg,
    pkgs,
    lib,
    theme ? null,
    ...
  }: let
    configFile = pkgs.writeText "btop.conf" (renderConf cfg.settings);
    # color_theme resolves against the dirs btop enumerates (user themes,
    # binary-relative share, --themes-dir); the extra dir is additive, so the
    # package's builtin themes stay selectable.
    themesDir = pkgs.writeTextFile {
      name = "btop-themes";
      destination = "/stylix.theme";
      text = themeFile theme;
    };
  in
    pkgs.mkWrapped {
      pkg = cfg.package;
      name = "btop";
      flags =
        lib.optionals (cfg.settings != {}) ["--config" "${configFile}"]
        ++ lib.optionals (theme != null) ["--themes-dir" "${themesDir}"];
    };
}
