{...}: {
  imports = [
    ./actual
    ./coder
    ./ezmtls
    ./headscale
    ./home-assistant
    ./immich
    ./mealie
    ./open-webui
    ./opencloud
    ./blocky.nix
    ./ddclient.nix
    ./gonic.nix
    ./hydroxide.nix
    ./libation.nix
    ./litellm.nix
    ./llamacpp-intel-arc.nix
    ./speaches.nix
    ./lldap.nix
    ./memos.nix
    ./pocket-id.nix
    ./postgresql.nix
    ./radicale.nix
    ./restic.nix
    ./searx.nix
    ./seerr.nix
    ./smtp.nix
    ./sunnycareboo.nix
    ./tailscale.nix
    ./vllm.nix
    ./zfs.nix
  ];
}
